import { test } from 'node:test';
import assert from 'node:assert/strict';
import * as core from '../src/index.js';

test('core module exports all expected members', () => {
  assert.equal(typeof core.createTenantConfig, 'function');
  assert.equal(typeof core.DEFAULT_TENANT_CONFIG, 'object');
  assert.equal(typeof core.HapticsService, 'function');
  assert.equal(typeof core.ShareService, 'function');
  assert.equal(typeof core.TelemetryService, 'function');
  assert.equal(typeof core.MarketPosition, 'object');
  assert.equal(typeof core.SearchService, 'function');
  assert.equal(typeof core.IngestService, 'function');
  assert.equal(typeof core.Dealer, 'function');
  assert.equal(typeof core.Vehicle, 'function');
  assert.equal(typeof core.haversineDistanceMiles, 'function');
  assert.equal(typeof core.TenantRegistry, 'function');
  assert.equal(typeof core.TENANT_STORAGE_KEY, 'string');
  assert.equal(typeof core.readTenantIdFromUrl, 'function');
  assert.equal(typeof core.readTenantIdFromStorage, 'function');
  assert.equal(typeof core.writeTenantIdToStorage, 'function');
  assert.equal(typeof core.resolveActiveTenantId, 'function');
  assert.equal(typeof core.DiscoveryService, 'function');
  assert.equal(typeof core.DiscoveryStage, 'object');
  assert.equal(typeof core.VendorAdapter, 'function');
  assert.equal(typeof core.CARBOYZ_TENANT_ID, 'string');
  assert.equal(typeof core.CARBOYZ_FLAGSHIP_PRESET, 'object');
  assert.equal(typeof core.SEED_ZIP_CODE, 'string');
  assert.equal(typeof core.SEED_ANCHOR, 'object');
  assert.equal(typeof core.CARBOYZ_HQ_DEALER_ID, 'string');
  assert.equal(Array.isArray(core.DIRECT_INVENTORY), true);
  assert.equal(Array.isArray(core.CARBOYZ_VENDOR_FEEDS), true);
  assert.equal(typeof core.seedDirectInventory, 'function');
});
